name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE] '
labels: enhancement

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature for this project!

  - type: input
    id: title
    attributes:
      label: Title
      description: A concise title for the feature request.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
